version: "3"
services:
  database:
    image: "mongo:latest"
    container_name: flashloans-database
    environment:
      - MONGO_INITDB_DATABASE=flashloans-database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password1
  mongo-dump:
    image: "mongo:latest"
    links:
      - database
    command: mongodump --uri mongodb://root:Password1@database:27017 -d admin
    ports:
      - "27017:27017"
    volumes:
      - ./flashloans-data/admin:/dump/admin
  # automate restore data
  # comment this code if you dont want restore data automacy
  # automatic data restore can be cause data duplicate, redundant.
  mongo-seed:
    image: "mongo:latest"
    links:
      - database
    volumes:
      - ./flashloans-data:/data
    command: mongorestore --uri mongodb://root:Password1@database:27017 -d admin /data/admin
  # all in docker
  app:
    image: node:12-alpine
    container_name: "flashloan-server"
    command: sh -c "yarn dev:docker"
    working_dir: /flashloans
    volumes:
      - ./:/flashloans
    ports:
      - "3001:3001"
